# Generated by Django 3.2.5 on 2021-07-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='genre',
            field=models.CharField(choices=[('1', 'Educational'), ('2', 'Fairy Tales'), ('3', 'Mystery'), ('4', 'Fictional')], max_length=80),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='language',
            field=models.CharField(choices=[('1', 'English'), ('2', 'German'), ('3', 'Chinese'), ('4', 'French'), ('5', 'Japanse')], max_length=80),
        ),
    ]
